import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from '@next/font/google'

const poppins = Poppins({
  weight: ['400', '600', '700'], // Choose font weights (regular, semi-bold, bold)
  subsets: ['latin'], // Choose the character subset you need
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
